 @:native("dfList") extern class DfList<T0> implements ArrayAccess<T0>{
	  public function new(capacity:Int) : Void;
	var Count(get,never) : Int;
	var IsReadOnly(get,never) : Bool;
	function Add(item : T0) : Void;
	@:final function AddRange(list : DfList<T0>) : Void;
	@:final function Any(predicate : Dynamic) : Bool;
	function Clear() : Void;
	@:final function Clone() : DfList<T0>;
	@:final function Concat(list : DfList<T0>) : DfList<T0>;
	function Contains(item : T0) : Bool;
	@:final function Convert<M0>() : DfList<M0>;
	@:final function CopyTo(array :Dynamic) : Void;
	@:final function Dequeue() : T0;
	function Dispose() : Void;
	@:final function Enqueue(item : T0) : Void;
	@:final function EnsureCapacity(Size : Int) : Void;
	@:final function First() : T0;
	@:final function FirstOrDefault() : T0;
	@:final function ForEach(action :Dynamic) : Void;
	@:noCompletion @:skipReflection function GetEnumerator():Dynamic;
	@:final function GetRange(index : Int, length : Int) : DfList<T0>;
	function IndexOf(item : T0) : Int;
	function Insert(index : Int, item : T0) : Void;
	@:final function InsertRange(index : Int, array : Dynamic) : Void;
	@:final function Last() : T0;
	@:final function LastOrDefault() : T0;
	@:final function Matching(predicate : Dynamic) : Int;
	@:final function Pop() : T0;
	@:final function Release() : Void;
	function Remove(item : T0) : Bool;
	@:final function RemoveAll(predicate : Dynamic) : Void;
	function RemoveAt(index : Int) : Void;
	@:final function RemoveRange(index : Int, length : Int) : Void;
	@:final function Reverse() : Void;
	@:final function Select<M0>(selector : Dynamic) : DfList<M0>;
	@:final function Sort() : Void;
	@:final function ToArray() : Dynamic;
	@:final function ToList() : Dynamic;
	@:final function TrimExcess() : Void;
	@:final function Where(predicate :Dynamic) : Dynamic;
	function get_Count() : Int;
	function get_IsReadOnly() : Bool;
	function get_Item(index : Int) : T0;
	function set_Item(index : Int, value : T0) : Void;
	@:final static function ClearPool() : Void;
	@:final static function Obtain() : DfList<Dynamic>;
}
